# https://taskfile.dev
version: '3'
tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  
  enable-os:
    cmds:
      - touch Taskfile_{{OS}}.yml

#includes:
#  build: ./Taskfile_{{OS}}.yml