# https://taskfile.dev
version: '3'
tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  version:
    desc: node version
    cmds:
    - node --version
    - which node

includes:
  os: ./Taskfile_{{OS}}.yml